id = "mojo-unofficial"
name = "Mojo (unofficial)"
description = "Mojo support (unofficial)"
version = "0.2.0"
schema_version = 1
authors = ["stano"]
repository = "https://github.com/MoSafi2/mz"

[grammars.mojo]
repository = "https://github.com/lsh/tree-sitter-mojo"
commit = "03966fb3f209bea86844aab3bd0f2158a5a8bb8d"

[language_servers.mojo-lsp]
name = "mojo-lsp"
language = "Mojo"
